### ISSUE TITLE
Errors creating tables

### ISSUE THREAD

**Issue by rhagarty** [bomeng/hspark_journey#4]
I tried to execute the first table creation script in `scripts/create_table.txt` and I got errors. Note, I just cut and paste the entire command into the shell prompt. Is there a different way to input these? Looks like a formatting issue.

The first error I got was:
`no viable alternative at input 'CREATE TABLE item ('(line 1, pos 19)

== SQL ==
CREATE TABLE item (
-------------------^^^

	at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:217)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:114)
	at org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:68)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
	at org.apache.spark.sql.hbase.HBaseSQLCliDriver$.process(HBaseSQLCliDriver.scala:228)
	at org.apache.spark.sql.hbase.HBaseSQLCliDriver$.main(HBaseSQLCliDriver.scala:161)
	at org.apache.spark.sql.hbase.HBaseSQLCliDriver.main(HBaseSQLCliDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
hspark> i_item_sk INTEGER,
17/10/16 17:07:42 INFO HBaseSQLCliDriver: Processing i_item_sk INTEGER,
17/10/16 17:07:42 INFO SparkSqlParser: Parsing command: i_item_sk INTEGER,
org.apache.spark.sql.catalyst.parser.ParseException:
mismatched input 'i_item_sk' expecting {'(', 'SELECT', 'FROM', 'ADD', 'DESC', 'WITH', 'VALUES', 'CREATE', 'TABLE', 'INSERT', 'DELETE', 'DESCRIBE', 'EXPLAIN', 'SHOW', 'USE', 'DROP', 'ALTER', 'MAP', 'SET', 'RESET', 'START', 'COMMIT', 'ROLLBACK', 'REDUCE', 'REFRESH', 'CLEAR', 'CACHE', 'UNCACHE', 'DFS', 'TRUNCATE', 'ANALYZE', 'LIST', 'REVOKE', 'GRANT', 'LOCK', 'UNLOCK', 'MSCK', 'EXPORT', 'IMPORT', 'LOAD'}(line 1, pos 0)`

**Comment by bomeng** [comment]
First, are you in the HSpark shell? Second, I suppose your copy and paste the following: 
`CREATE TABLE item (
i_item_sk INTEGER,
i_item_id STRING,
i_rec_start_date LONG,
i_rec_end_date LONG,
i_item_desc STRING,
i_current_price FLOAT,
i_wholesale_cost FLOAT,
i_brand_id INTEGER,
i_brand STRING,
i_class_id INTEGER,
i_class STRING,
i_category_id INTEGER,
i_category STRING,
i_manufact_id INTEGER,
i_manufact STRING,
i_size STRING,
i_formulation STRING,
i_color STRING,
i_units STRING,
i_container STRING,
i_manager_id INTEGER,
i_product_name STRING)
TBLPROPERTIES(
'hbaseTableName'='item_htable',
'keyCols'='i_item_sk',
'nonKeyCols'='i_item_id,f,i_item_id;i_rec_start_date,f,i_rec_start_date;i_rec_end_date,f,i_rec_end_date;i_item_desc,f,i_item_desc;i_current_price,f,i_current_price;i_wholesale_cost,f,i_wholesale_cost;i_brand_id,f,i_brand_id;i_brand,f,i_brand;i_class_id,f,i_class_id;i_class,f,i_class;i_category_id,f,i_category_id;i_category,f,i_category;i_manufact_id,f,i_manufact_id;i_manufact,f,i_manufact;i_size,f,i_size;i_formulation,f,i_formulation;i_color,f,i_color;i_units,f,i_units;i_container,f,i_counter;i_manager_id,f,i_manager_id;i_product_name,f,i_product_name')
`

**Comment by bomeng** [comment]
I've added more materials to the troubleshooting sections to address those issues.
